;; Languarge Environment
(set-language-environment "Japanese")
(when windows-p
  (prefer-coding-system 'sjis-unix)
  (setq default-buffer-file-coding-system 'sjis-unix)
  (set-buffer-file-coding-system 'sjis-unix)
  (set-terminal-coding-system 'sjis-unix)
  (set-keyboard-coding-system 'sjis-unix)
  (set-clipboard-coding-system 'sjis-unix)
  (set-default-coding-systems 'sjis-unix)
  )

(when (or darwin-p linux-p)
  (prefer-coding-system 'utf-8-unix)
  (setq default-buffer-file-coding-system 'utf-8)
  (set-buffer-file-coding-system 'utf-8-unix)
  (set-terminal-coding-system 'utf-8-unix)
  (set-keyboard-coding-system 'utf-8-unix)
  (set-clipboard-coding-system 'utf-8-unix)
  (set-default-coding-systems 'utf-8-unix)
  )
