(when (require 'go-mode nil t)
  (require 'company-go nil t)

  (add-hook `go-mode-hook `company-mode)
  (add-hook `go-mode-hook (lambda()
			    (local-set-key (kbd "M-.") `godef-jump)
;			    (set (make-local-variable `company-backends) `(company-go))
			    (company-mode)
			    (setq indent-tabs-mode t)
			    (setq c-basic-offset 4)
			    (setq tab-width 4)))
  )
